config/routes.rb
Spotlight::Application.routes.draw do
  resources :users do
    resources :podcasts do
      resources :episodes
    end
  end

  resources :podcasts, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]

  root 'main#home'
  match '/about',  to: 'main#about',    via: 'get'
  match '/signup', to: 'users#new',     via: 'get'
  match '/login',  to: 'sessions#new',  via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

end

app/models/episode.rb
class Episode < ActiveRecord::Base
	belongs_to :podcast, dependent: :destroy
	default_scope -> { order('created_at DESC') }
	validates :title, presence: true, length: { maximum: 100 }
	validates :description, presence: true, length: { maximum: 500 }
	validates :min_upvotes, presence: true, length: {minimum: 2}, numericality: { only_integer: true }
	#KEEP WORKING ON THIS. NEEDS TO BE FURTHER VALIDATED!!
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
	belongs_to :user
	has_many :episodes
	validates :user_id, presence: true
	validates :name, presence: true, length: { maximum: 100 }
	validates :description, presence: true, length: { maximum: 140 }	
end

app/models/submission.rb
class Submission < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :podcasts, dependent: :destroy
	before_create :create_remember_token
	before_save { self.email = email.downcase }
	validates :fname, presence: true
	validates :lname, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
				uniqueness: { case_sensitive: false }
	validates :username, presence: true
	validates :password, length: { minimum: 8 }

	has_secure_password

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.hash(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
			self.remember_token = User.hash(User.new_remember_token)
		end
end

app/models/users.rb
class Users < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :fname, presence: true
	validates :lname, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
				uniqueness: { case_sensitive: false }
	validates :username, presence: true
	validates :password, presence: true, length: { minimum: 8 }

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/chat_controller.rb
class ChatController < WebsocketRails::BaseController
  include ActionView::Helpers::SanitizeHelper
  
  def initialize_session
    # perform application setup here
    controller_store[:message_count] = 0
    puts "---------------\nWE OUT HERE FAM YEEZUS WALKS WITH ME\n---------------\n"
  end

  def client_connected
  end 

  #User votes a comment up
  def upvote_comment 
  	
  end

  #user takes back their vote
  def unvote_comment
  	
  end

  #user submits a new comment
  def new_comment
    udata = {:message => data, :stime => Time.now.strftime("%I:%M %p")}
  	broadcast_message :add_user_submission, udata
  end

  def new_comment_host
    udata = {:message => data, :stime => Time.now.strftime("%I:%M %p")}
    broadcast_message :add_host_submission, udata
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
	respond_to :html, :json, :xml

	def new
		@podcast = User.find(params[:user_id]).podcasts.find(params[:podcast_id])
		@episode = @podcast.episodes.build
		respond_with(@episode)
	end

	def create
		@podcast = User.find(params[:user_id]).podcasts.find(params[:podcast_id])
		@episode = @podcast.episodes.build(epcreate_params)
		if @episode.save 
			flash[:success] = "3, 2, 1.."
			redirect_to user_podcast_episode_path(params[:user_id], params[:podcast_id], @episode.id)
		else
			render 'new'
		end
	end

	def show
		@podcast = User.find(params[:user_id]).podcasts.find(params[:podcast_id])
	end

	private
		def epcreate_params
			params.require(:episode).permit(:title, :description, :upvote_type, :min_upvotes)
		end	
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
	# before_action :signed_in_user only: [:create, :destroy]
	respond_to :html, :json, :xml

	def new
		@user = User.find(params[:user_id])
		@podcast = @user.podcasts.build
		respond_with(@podcast)
	end

	def create
		@user = User.find(params[:user_id])
		@podcast = @user.podcasts.build(podcast_params)
		if @podcast.save
			flash[:success] = "Podcast created"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def index
		@podcast = Podcast.all
	end

	def show
		@podcast = User.find(params[:user_id]).podcasts.find(params[:id])
	end

	def destroy
		@podcast = User.find(params[:user_id]).podcasts.find(params[:id])
		@podcast.destroy
		redirect_back_or root_url
	end

	private
		def podcast_params
			params.require(:podcast).permit(:name, :description)
		end	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(username: params[:session][:username])
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/test_controller.rb
class TestController < WebsocketRails::BaseController
  def init
  	puts "---------------\nWE OUT HERE FAM YEEZUS WALKS WITH ME\n---------------\n"
  end
end

app/controllers/testsock_controller.rb
class TestsockController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(update_user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  private
  	def user_params
  		params.require(:user).permit(:fname, :lname, :username, 
  			:email, :password, :password_confirmation)
  	end

    def update_user_params
      params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to login_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
	def ishosting?(user)
		@user = User.find(params[:user_id])
		current_user?(@user)
	end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.hash(remember_token))
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user?(user)
		user == current_user
	end

	def current_user
		remember_token = User.hash(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		current_user.update_attribute(:remember_token,
			User.hash(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

app/helpers/testsock_helper.rb
module TestsockHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/episodes/_navbar.html.erb
<div class="navbar">
	<div class="navbar-inner">
			<%= link_to '#', class: "brand" do %><%= text.html_safe %><% end %>
	</div>
</div>

app/views/episodes/_sidebar.html.erb
<ul class="nav nav-list">
	<li><h1><%= @podcast.name %></h1></li>
	<li class="podcover"><%= image_tag 'podcastcover.jpg', alt: "chocolate" %></li>
	<li class="poddescript"><%= @podcast.description %></li>
	<!-- make it if-contact-exists-soemthing-toolazyatm
	<li class="list-header">Contact</li>-->
	<!-- make if-admin-check-->
	<% if current_user?(@podcast.user) %>
	<li class="podbuttons"></li>
	<%= link_to '#', class: "btn btn-success btn-block" do %>
		<i class="icon-bullhorn"></i> Start Broadcast
		<% end %>
		<%= link_to '#',
            data: { confirm: "You sure?" }, class: "btn btn-danger btn-block" do %>
		<i class="icon-trash"></i> Remove Podcast
		<% end %>
	<% end %>
</ul>

app/views/episodes/new.html.erb
<% provide(:title, "Start a new episode") %>
<div class="row">
	<div class="span3">
		<%= render 'sidebar' %>
	</div>
	<div class="span7">
		<%= render partial: 'navbar', locals: {text: "Start a Broadcast"} %>
		<div>
		<%= form_for(@episode, :url=>user_podcast_episodes_path(params[:user_id], params[:podcast_id])) do |f| %>
			<% if @episode.errors.any? %>
				<div class="alert alert-error">
				<ul>
					<% @episode.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
					
				</ul>
				</div>
			<% end %>
			<%= f.label :title %>
			<%= f.text_field :title %>

			<%= f.label :description %>
			<%= f.text_field :description %>

			<br>Voting System<br>
			<%= f.radio_button :upvote_type, "Number" %>
			<%= f.label :upvote_type_number, "Number" %>
			<%= f.radio_button :upvote_type, "Percent" %>
			<%= f.label :upvote_type_percent, "Percent" %>

			<%= f.label :min_upvotes, "Voting Threshold" %>
			<%= f.number_field :min_upvotes, value: "0" %>
			<p>
			<%= f.submit "Start a new Episode", class: "btn btn-primary btn-large" %>
			</p>
		</div>
	</div>
<% end %>

app/views/episodes/show.html.erb
<% provide(:title, "Start a new episode") %>
<div class="row">
	<div class="span3">
		<%= render 'sidebar'%>
	</div>
	<div class="span9">
		<% if ishosting?(current_user) %>
		<%= render partial: 'navbar', locals: {text: "You're broadcasting!"}  %>
		<div>
			<div name="audio player">
				Streaming media player thingy
			</div>
			<div class="well hostlog">
				<h4 class="wellhead" data-uri="<%= request.host %>:<%= request.port %>/websocket">User submission past threshold</h4>
				<table class="table" id="user-accepted-table">
					<!-- User submissions past threshold goes here-->
				</table>
			</div>
			<input type="text" class="span8" id="message">
			<button type="submit" class="btn" id="sendhost">Submit</button>
			<div class="well usersubs">
				<h4 class="wellhead" data-uri="<%= request.host %>:<%= request.port %>/websocket">Your Activity Log</h4>
				<table class="table" id="host-table">
					<!-- host activity goes here-->
				</table>
			</div>
		</div>
		<% else %>
		<%= render partial: 'navbar', locals: {text: "Listening to #{Episode.find(params[:id]).title}" }  %>
		<div>
			<div name="audio player">
				Audio Player
			</div>
			<div class="well hostlog" data-uri="<%= request.host %>:<%= request.port %>/websocket">
				<h4 class="wellhead">Host's Activity Log</h4>
				<table class="table" id="host-table">
					<!-- host activity goes here-->
				</table>
			</div>
			<input type="text" class="span8" id="message">
			<button type="submit" class="btn" id="send">Submit</button>
			<div class="well usersubs" data-uri="<%= request.host %>:<%= request.port %>/websocket">
				<h4 class="wellhead">User Submissions</h4>
				<table class="table" id="user-submissions">
					<!-- User submissions goes here-->
				</table>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/main/about.html.erb
<% provide(:title, 'About') %>
<div class="center hero-unit">
  <h1>About Spotlight</h1>

  <h2>
    something
  </h2>
</div>

app/views/main/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Spotlight</h1>
  <% if signed_in? %>
  	<% if @current_user.podcasts.any? %>
  		<ul class="nav nav-tabs nav-stacked" style="text-align:left;">
  		<% @current_user.podcasts.each do |podcast| %>
        <%= render partial: "layouts/list_podcasts", locals: {podcast: podcast} %>

  		<% end %>
      </ul>
	  	<%= link_to "Start another Podcast", new_user_podcast_path(current_user[:id]), class: "btn btn-large btn-primary" %>
  	<% else %>
      <p>
    	<%= link_to "Start a Podcast", new_user_podcast_path(current_user[:id]), class: "btn btn-large btn-primary" %>
      </p>
  	<% end %>
    <p>
    <%= link_to "Or Watch a Podcast", podcasts_path, class: "btn btn-secondary" %>
    </p>
  <% else %>
  <h2>homepage</h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/podcasts/_episode.html.erb
<div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#epaccord" href="#<%= episode.podcast_id %><%= episode.id %>">
        <%= episode.title %>
      </a>
</div>
<div id="<%= episode.podcast_id %><%= episode.id %>" class="accordion-body collapse">
  <div class="accordion-inner">
    <%= episode.description %>
    <br>
    <% #link_to user_podcast_episode_path(params[:user_id], episode.podcast_id, episode.id) %>
    <a href="#<%= episode.podcast_id %><%= episode.id %>">
        Click here to listen &amp; discuss
      </a>
  </div>
</div>

app/views/podcasts/_sidebar.html.erb
<ul class="nav nav-list">
	<li><h1><%= @podcast.name %></h1></li>
	<li class="podcover"><%= image_tag 'podcastcover.jpg', alt: "chocolate" %></li>
	<li class="poddescript"><%= @podcast.description %></li>
	<!-- make it if-contact-exists-soemthing-toolazyatm
	<li class="list-header">Contact</li>-->
	<!-- make if-admin-check-->
	<% if current_user?(@podcast.user) %>
	<li class="podbuttons"></li>
	<%= link_to new_user_podcast_episode_path(current_user[:id], @podcast[:id]), class: "btn btn-success btn-block" do %>
		<i class="icon-bullhorn"></i> Start Broadcast
		<% end %>
		<%= link_to user_podcast_path, method: :delete,
            data: { confirm: "You sure?" }, class: "btn btn-danger btn-block" do %>
		<i class="icon-trash"></i> Remove Podcast
		<% end %>
	<% end %>
</ul>

app/views/podcasts/index.html.erb
<h1>All Podcasts</h1>
<ul class="nav nav-tabs nav-stacked" style="text-align:left;">
  		<% @podcast.each do |podcast| %>
        	<%= render partial: "layouts/list_podcasts", locals: {podcast: podcast} %>
        <% end %>
  	</ul>
	

app/views/podcasts/new.html.erb
<% provide(:title, "Make a Podcast") %>
<h1>Start a Podcast</h1>

<%= form_for(@podcast, :url=>user_podcasts_path(@user)) do |f| %>
	<% if @podcast.errors.any? %>
		<div class="alert alert-error">
		<ul>
			<% @podcast.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			
		</ul>
		</div>
	<% end %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :description %>
	<%= f.text_field :description %>
	<p>
	<%= f.submit "Create Podcast", class: "btn btn-primary btn-large" %>
	</p>
<% end %>

app/views/podcasts/show.html.erb
<% provide(:title, @podcast.name.html_safe) %>
<!--<div class="hero-unit">-->
<div class="row">
	<div class="span3">
		<%= render 'sidebar' %>
	</div>
	<div class="span7">
		<div class="navbar">
			<div class="navbar-inner">
				<% if @podcast.live %>
					<%= link_to '#', class: "brand" do %>Currenty Live<% end %>
				<% else %>
					<%= link_to '#', class: "brand" do %>Off-Air<% end %>
				<% end %>
			</div>
		</div>
		<div>
			<h2 class="lpadding h2ep">Episodes</h2>
			<% if @podcast.episodes.any? %>
				<div class="accordion" id="epaccord">
					<div class="accordion-group">
						<% @podcast.episodes.each do |episode| %>
						<%= render partial: "episode", locals: {episode: episode} %>
						<% end %>
					</div>
				</div>
			<% else %>
				<p class="lpadding"><b><%= @podcast.name %></b> has not broadcasted an episode yet.</p>
			<% end %>
		</div>
	</div>
</div>
</div>

app/views/testsock/index.html.erb
<h1>Testsock#index</h1>
<p>Find me in app/views/testsock/index.html.erb</p>

app/views/users/_errorform.html.erb
<% if @user.errors.any? %>
	<div class="alert alert-error">
		<strong>Error! Unable to create account:</strong><br>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		</ul>
		<% end %>
	</div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Update Profile") %>
<h1>Update Profile</h1>
<div class="row">
	<div class="span6 offset4">
		<%= form_for(@user) do |f| %>
		<%= render 'users/errorform' %>

		<%= f.label :fname, "First Name" %> 
		<%= f.text_field :fname %>

		<%= f.label :lname, "Last Name" %>
		<%= f.text_field :lname %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password, "Please enter current password or type a new one" %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation, "Confirm Password" %>
		<%= f.password_field :password_confirmation %>
		<p>
		<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		</p>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<div class="row-fluid" style="margin:0 auto;float:none;">
	<div class="span3" style="margin:0 auto;float:none;">
		<h1>New User</h1>
		<%= form_for(@user) do |f| %>
		<%= render 'users/errorform' %>
			<p>
			<%= f.label :fname, "First Name" %>
			<%= f.text_field :fname %>
			</p>
			<p>
			<%= f.label :lname, "Last Name" %>
			<%= f.text_field :lname %>
			</p>
			<p>
			<%= f.label :email, "Email" %>
			<%= f.text_field :email, type: "email"%>
			</p>
			<p>
			<%= f.label :username, "Username" %>
			<%= f.text_field :username %>
			</p>
			<p>
			<%= f.label :password, "Password" %>
			<%= f.password_field :password %>
			</p>
			<p>
			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>
			</p>
			<p style="text-align:center;">
			<%= f.submit "Create Account", class: "btn btn-primary" %>
			</p>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h1>User Information</h1>
<p><%= @user.fname %> <%= @user.lname %> (<%= @user.username %>), <%= @user.email %></p>