config/routes.rb
Spotlight::Application.routes.draw do
  resources :users do
    resources :podcasts do
      resources :episodes
    end
  end

  resources :podcasts, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]

  root 'main#home'
  match '/about',  to: 'main#about',    via: 'get'
  match '/signup', to: 'users#new',     via: 'get'
  match '/login',  to: 'sessions#new',  via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

end

app/models/episode.rb
class Episode < ActiveRecord::Base
	belongs_to :podcast, dependent: :destroy
	default_scope -> { order('created_at DESC') }
	validates :title, presence: true, length: { maximum: 100 }
	validates :description, presence: true, length: { maximum: 500 }
	validates :min_upvotes, presence: true, length: {minimum: 2}, numericality: { only_integer: true }
	#KEEP WORKING ON THIS. NEEDS TO BE FURTHER VALIDATED!!
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
	belongs_to :user
	has_many :episodes
	validates :user_id, presence: true
	validates :name, presence: true, length: { maximum: 100 }
	validates :description, presence: true, length: { maximum: 140 }	
end

app/models/submission.rb
class Submission < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :podcasts, dependent: :destroy
	before_create :create_remember_token
	before_save { self.email = email.downcase }
	validates :fname, presence: true
	validates :lname, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
				uniqueness: { case_sensitive: false }
	validates :username, presence: true
	validates :password, length: { minimum: 8 }

	has_secure_password

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.hash(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
			self.remember_token = User.hash(User.new_remember_token)
		end
end

app/models/users.rb
class Users < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :fname, presence: true
	validates :lname, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
				uniqueness: { case_sensitive: false }
	validates :username, presence: true
	validates :password, presence: true, length: { minimum: 8 }

	has_secure_password
end

app/controllers/chat_controller.rb
class ChatController < WebsocketRails::BaseController
  include ActionView::Helpers::SanitizeHelper
  
  def initialize_session
    # perform application setup here
    controller_store[:message_count] = 0
    puts "---------------\nWE OUT HERE FAM YEEZUS WALKS WITH ME\n---------------\n"
  end

  def client_connected
  end 

  #User votes a comment up
  def upvote_comment 
  	
  end

  #user takes back their vote
  def unvote_comment
  	
  end

  #user submits a new comment
  def new_comment
    udata = {:message => data, :stime => Time.now.strftime("%I:%M %p")}
  	broadcast_message :add_user_submission, udata
  end

  def new_comment_host
    udata = {:message => data, :stime => Time.now.strftime("%I:%M %p")}
    broadcast_message :add_host_submission, udata
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
	respond_to :html, :json, :xml

	def new
		@podcast = User.find(params[:user_id]).podcasts.find(params[:podcast_id])
		@episode = @podcast.episodes.build
		respond_with(@episode)
	end

	def create
		@podcast = User.find(params[:user_id]).podcasts.find(params[:podcast_id])
		@episode = @podcast.episodes.build(epcreate_params)
		if @episode.save 
			flash[:success] = "3, 2, 1.."
			redirect_to user_podcast_episode_path(params[:user_id], params[:podcast_id], @episode.id)
		else
			render 'new'
		end
	end

	def show
		@podcast = User.find(params[:user_id]).podcasts.find(params[:podcast_id])
	end

	private
		def epcreate_params
			params.require(:episode).permit(:title, :description, :upvote_type, :min_upvotes)
		end	
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
	# before_action :signed_in_user only: [:create, :destroy]
	respond_to :html, :json, :xml

	def new
		@user = User.find(params[:user_id])
		@podcast = @user.podcasts.build
		respond_with(@podcast)
	end

	def create
		@user = User.find(params[:user_id])
		@podcast = @user.podcasts.build(podcast_params)
		if @podcast.save
			flash[:success] = "Podcast created"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def index
		@podcast = Podcast.all
	end

	def show
		@podcast = User.find(params[:user_id]).podcasts.find(params[:id])
	end

	def destroy
		@podcast = User.find(params[:user_id]).podcasts.find(params[:id])
		@podcast.destroy
		redirect_back_or root_url
	end

	private
		def podcast_params
			params.require(:podcast).permit(:name, :description)
		end	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(username: params[:session][:username])
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/test_controller.rb
class TestController < WebsocketRails::BaseController
  def init
  	puts "---------------\nWE OUT HERE FAM YEEZUS WALKS WITH ME\n---------------\n"
  end
end

app/controllers/testsock_controller.rb
class TestsockController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(update_user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  private
  	def user_params
  		params.require(:user).permit(:fname, :lname, :username, 
  			:email, :password, :password_confirmation)
  	end

    def update_user_params
      params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to login_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
	def ishosting?(user)
		@user = User.find(params[:user_id])
		current_user?(@user)
	end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.hash(remember_token))
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user?(user)
		user == current_user
	end

	def current_user
		remember_token = User.hash(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		current_user.update_attribute(:remember_token,
			User.hash(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

app/helpers/testsock_helper.rb
module TestsockHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "spotlight", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
					<% if signed_in? %>
			            <li><%= link_to "Podcasts", podcasts_path %></li>
			            <li id="fat-menu" class="dropdown">
			              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
			                Account <b class="caret"></b>
			              </a>
			              <ul class="dropdown-menu">
			                <li><%= link_to "Profile", current_user %></li>
			                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
			                <li class="divider"></li>
			                <li>
			                  <%= link_to "Logout", logout_path, method: "delete" %>
			                </li>
			              </ul>
			            </li>
			        <% else %>
			            <li><%= link_to "Login", login_path %></li>
			        <% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_list_podcasts.html.erb
<li>
	<%= link_to user_podcast_path(podcast.user_id, podcast.id) do %>
	<%= podcast.name %> <br><small><%= podcast.description %></small>
	<% end %>
</li>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_signedin.html.erb
<% if signed_in? %>
  # Links for signed-in users
<% else %>
  # Links for non-signed-in-users
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= render 'layouts/flash' %>
		<%= yield %>
	</div>
</body>
</html>